// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: schema/authenticator.proto

package authenticatorgrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthenticatePasswordReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *AuthenticatePasswordReq) Reset() {
	*x = AuthenticatePasswordReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_authenticator_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthenticatePasswordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticatePasswordReq) ProtoMessage() {}

func (x *AuthenticatePasswordReq) ProtoReflect() protoreflect.Message {
	mi := &file_schema_authenticator_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticatePasswordReq.ProtoReflect.Descriptor instead.
func (*AuthenticatePasswordReq) Descriptor() ([]byte, []int) {
	return file_schema_authenticator_proto_rawDescGZIP(), []int{0}
}

func (x *AuthenticatePasswordReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuthenticatePasswordReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AuthenticatePasswordResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *AuthenticatePasswordResponse) Reset() {
	*x = AuthenticatePasswordResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_authenticator_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthenticatePasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticatePasswordResponse) ProtoMessage() {}

func (x *AuthenticatePasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schema_authenticator_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticatePasswordResponse.ProtoReflect.Descriptor instead.
func (*AuthenticatePasswordResponse) Descriptor() ([]byte, []int) {
	return file_schema_authenticator_proto_rawDescGZIP(), []int{1}
}

func (x *AuthenticatePasswordResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_schema_authenticator_proto protoreflect.FileDescriptor

var file_schema_authenticator_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74,
	0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x74, 0x6f,
	0x79, 0x22, 0x51, 0x0a, 0x17, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74,
	0x65, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x22, 0x34, 0x0a, 0x1c, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69,
	0x63, 0x61, 0x74, 0x65, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x32, 0x68, 0x0a, 0x0d, 0x41, 0x75,
	0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x57, 0x0a, 0x14, 0x41,
	0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x65, 0x50, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x12, 0x1c, 0x2e, 0x74, 0x6f, 0x79, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e,
	0x74, 0x69, 0x63, 0x61, 0x74, 0x65, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65,
	0x71, 0x1a, 0x21, 0x2e, 0x74, 0x6f, 0x79, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69,
	0x63, 0x61, 0x74, 0x65, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x1a, 0x5a, 0x18, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2f, 0x61,
	0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x67, 0x72, 0x70, 0x63,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_schema_authenticator_proto_rawDescOnce sync.Once
	file_schema_authenticator_proto_rawDescData = file_schema_authenticator_proto_rawDesc
)

func file_schema_authenticator_proto_rawDescGZIP() []byte {
	file_schema_authenticator_proto_rawDescOnce.Do(func() {
		file_schema_authenticator_proto_rawDescData = protoimpl.X.CompressGZIP(file_schema_authenticator_proto_rawDescData)
	})
	return file_schema_authenticator_proto_rawDescData
}

var file_schema_authenticator_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_schema_authenticator_proto_goTypes = []interface{}{
	(*AuthenticatePasswordReq)(nil),      // 0: toy.AuthenticatePasswordReq
	(*AuthenticatePasswordResponse)(nil), // 1: toy.AuthenticatePasswordResponse
}
var file_schema_authenticator_proto_depIdxs = []int32{
	0, // 0: toy.Authenticator.AuthenticatePassword:input_type -> toy.AuthenticatePasswordReq
	1, // 1: toy.Authenticator.AuthenticatePassword:output_type -> toy.AuthenticatePasswordResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_schema_authenticator_proto_init() }
func file_schema_authenticator_proto_init() {
	if File_schema_authenticator_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_schema_authenticator_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthenticatePasswordReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_authenticator_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthenticatePasswordResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_schema_authenticator_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_schema_authenticator_proto_goTypes,
		DependencyIndexes: file_schema_authenticator_proto_depIdxs,
		MessageInfos:      file_schema_authenticator_proto_msgTypes,
	}.Build()
	File_schema_authenticator_proto = out.File
	file_schema_authenticator_proto_rawDesc = nil
	file_schema_authenticator_proto_goTypes = nil
	file_schema_authenticator_proto_depIdxs = nil
}
