// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: schema/calculator.proto

package calculatorgrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Values struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X int32 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y int32 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *Values) Reset() {
	*x = Values{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_calculator_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Values) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Values) ProtoMessage() {}

func (x *Values) ProtoReflect() protoreflect.Message {
	mi := &file_schema_calculator_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Values.ProtoReflect.Descriptor instead.
func (*Values) Descriptor() ([]byte, []int) {
	return file_schema_calculator_proto_rawDescGZIP(), []int{0}
}

func (x *Values) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Values) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type SubstractValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int32 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *SubstractValue) Reset() {
	*x = SubstractValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_calculator_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubstractValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubstractValue) ProtoMessage() {}

func (x *SubstractValue) ProtoReflect() protoreflect.Message {
	mi := &file_schema_calculator_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubstractValue.ProtoReflect.Descriptor instead.
func (*SubstractValue) Descriptor() ([]byte, []int) {
	return file_schema_calculator_proto_rawDescGZIP(), []int{1}
}

func (x *SubstractValue) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type AddValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int32 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *AddValue) Reset() {
	*x = AddValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_calculator_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddValue) ProtoMessage() {}

func (x *AddValue) ProtoReflect() protoreflect.Message {
	mi := &file_schema_calculator_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddValue.ProtoReflect.Descriptor instead.
func (*AddValue) Descriptor() ([]byte, []int) {
	return file_schema_calculator_proto_rawDescGZIP(), []int{2}
}

func (x *AddValue) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_schema_calculator_proto protoreflect.FileDescriptor

var file_schema_calculator_proto_rawDesc = []byte{
	0x0a, 0x17, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2f, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61,
	0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x74, 0x6f, 0x79, 0x22, 0x24,
	0x0a, 0x06, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x01, 0x79, 0x22, 0x26, 0x0a, 0x0e, 0x53, 0x75, 0x62, 0x73, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x20, 0x0a, 0x08,
	0x41, 0x64, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x32, 0x5e,
	0x0a, 0x0a, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x2d, 0x0a, 0x09,
	0x53, 0x75, 0x62, 0x73, 0x74, 0x72, 0x61, 0x63, 0x74, 0x12, 0x0b, 0x2e, 0x74, 0x6f, 0x79, 0x2e,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x1a, 0x13, 0x2e, 0x74, 0x6f, 0x79, 0x2e, 0x53, 0x75, 0x62,
	0x73, 0x74, 0x72, 0x61, 0x63, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x21, 0x0a, 0x03, 0x41,
	0x64, 0x64, 0x12, 0x0b, 0x2e, 0x74, 0x6f, 0x79, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x1a,
	0x0d, 0x2e, 0x74, 0x6f, 0x79, 0x2e, 0x41, 0x64, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x17,
	0x5a, 0x15, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2f, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61,
	0x74, 0x6f, 0x72, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_schema_calculator_proto_rawDescOnce sync.Once
	file_schema_calculator_proto_rawDescData = file_schema_calculator_proto_rawDesc
)

func file_schema_calculator_proto_rawDescGZIP() []byte {
	file_schema_calculator_proto_rawDescOnce.Do(func() {
		file_schema_calculator_proto_rawDescData = protoimpl.X.CompressGZIP(file_schema_calculator_proto_rawDescData)
	})
	return file_schema_calculator_proto_rawDescData
}

var file_schema_calculator_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_schema_calculator_proto_goTypes = []interface{}{
	(*Values)(nil),         // 0: toy.Values
	(*SubstractValue)(nil), // 1: toy.SubstractValue
	(*AddValue)(nil),       // 2: toy.AddValue
}
var file_schema_calculator_proto_depIdxs = []int32{
	0, // 0: toy.Calculator.Substract:input_type -> toy.Values
	0, // 1: toy.Calculator.Add:input_type -> toy.Values
	1, // 2: toy.Calculator.Substract:output_type -> toy.SubstractValue
	2, // 3: toy.Calculator.Add:output_type -> toy.AddValue
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_schema_calculator_proto_init() }
func file_schema_calculator_proto_init() {
	if File_schema_calculator_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_schema_calculator_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Values); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_calculator_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubstractValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_calculator_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_schema_calculator_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_schema_calculator_proto_goTypes,
		DependencyIndexes: file_schema_calculator_proto_depIdxs,
		MessageInfos:      file_schema_calculator_proto_msgTypes,
	}.Build()
	File_schema_calculator_proto = out.File
	file_schema_calculator_proto_rawDesc = nil
	file_schema_calculator_proto_goTypes = nil
	file_schema_calculator_proto_depIdxs = nil
}
